apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-cluster-remote-machines
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/GOodCoffeeLover/personal-mini-projects.git
    targetRevision: main
    path: lab-cluster/cluster/remote-machines
  destination:
    server: https://kubernetes.default.svc
    namespace: lab-cluster
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - Prune=false
    - ServerSideApply=true
