apiVersion: v1
kind: Namespace
metadata:
  name: capi-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubeadm-bootstrap-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubeadm-control-plane-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: k0sproject-k0smotron-infrastructure-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: helm-addon-system
