apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    max.home:53 {
        log
        errors
        cache 100
        health {
           lameduck 5s
        }
        ready
        file /etc/coredns/max.db
        forward . 77.88.8.8
        reload
    }
    .:53 {
        log
        errors
        cache 100
        health {
           lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . 77.88.8.8
        loop
        reload
        loadbalance
    }
  max.db: |
    ; https://bind9.readthedocs.io/en/v9.18.14/chapter3.html#example-com-base-zone-file

    ; base zone file for max.home
    $TTL 2d    ; default TTL for zone
    $ORIGIN max.home. ; base domain-name

    ; Start of Authority RR defining the key characteristics of the zone (domain)
    @         IN      SOA      ns.max.home. hostmaster.max.home. (
                                    2401022122 ; serial number
                                    12h        ; refresh
                                    15m        ; update retry
                                    3w         ; expire
                                    2h         ; minimum ttl
                                    )
    ns    IN      A       192.168.1.199
    toshiba-ubuntu-server-2204   IN      A       192.168.1.199
    ; name server RR for the domain
    @          IN      NS      ns.max.home.

    ; domain hosts includes NS and MX records defined above
    ; plus any others required
    ; for instance a user query for the A RR of example.max.home will
    ; return the IPv4 address 192.168.254.6 from this zone file
    ; aliases ftp (ftp server) to an external domain
    *.k8s      IN       A     192.168.1.2
