---
apiVersion: v1
kind: Namespace
metadata:
  name: registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
      labels:
        app: registry
      name: registry
      namespace: registry
    spec:
      containers:
      - name: registry
        image: distribution/distribution:2.8.3
        imagePullPolicy: IfNotPresent
        env:
        - name: REGISTRY_STORAGE_DELETE_ENABLED
          value: "true"
        volumeMounts:
        - name: registry
          mountPath: /var/lib/registry
        ports:
        - containerPort: 5000
        - containerPort: 5001
      - name: garbage-collector
        image: distribution/distribution:2.8.3
        imagePullPolicy: IfNotPresent
        command:
          - sh
          - -c
          - |-
            while true; do
            sleep 1800
            registry garbage-collect --delete-untagged /etc/docker/registry/config.yml 
            done
        env:
        - name: REGISTRY_STORAGE_DELETE_ENABLED
          value: "true"
        volumeMounts:
        - name: registry
          mountPath: /var/lib/registry
      volumes:
      - name: registry
        persistentVolumeClaim:
          claimName: registry-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
  namespace: registry
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 64Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: registry
  name: registry
  namespace: registry
spec:
  ports:
  - name: 80-5000
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: registry
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: registry-ing
  namespace: registry
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: Authorization,Accept,Cache-Control
    nginx.ingress.kubernetes.io/cors-allow-methods: HEAD,GET,OPTIONS,DELETE
    nginx.ingress.kubernetes.io/cors-allow-origin: http://registry-ui.k8s.max.home
    nginx.ingress.kubernetes.io/cors-expose-headers: Docker-Content-Digest
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: registry.k8s.max.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: registry
            port:
              number: 80
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: clean-registry
  namespace: registry
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      name: clean-registry
    spec:
      activeDeadlineSeconds: 180
      template:
        spec:
          containers:
          - name: registry-cli
            args:
            - --host=http://registry.k8s.max.home
            - --delete
            - --image=static-site-controller
            # https://github.com/andrey-pohilko/registry-cli?tab=readme-ov-file#docker-image
            image: anoxis/registry-cli
            imagePullPolicy: IfNotPresent
          dnsPolicy: ClusterFirst
          restartPolicy: Never 
          nodeSelector:
            kubernetes.io/arch: amd64
            
  schedule: 12 */1 * * *
  successfulJobsHistoryLimit: 1
---
