---
apiVersion: v1
kind: Namespace
metadata:
  name: wol
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: wol-toshiba
  namespace: wol
spec:
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 300
      activeDeadlineSeconds: 180
      template:
        spec:
          hostNetwork: true
          containers:
          - image: bltavares/wol
            env:
            - name: mac
              value: E8:40:F2:2E:AF:09
            imagePullPolicy: IfNotPresent
            name: wol
          restartPolicy: Never
          terminationGracePeriodSeconds: 5
  schedule: 0 11 */2 * *
  successfulJobsHistoryLimit: 1
  suspend: false
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: shutdown-toshiba
  namespace: wol
spec:
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 300
      activeDeadlineSeconds: 180
      template:
        spec:
          containers:
          - command:
            - nsenter
            - --target
            - "1"
            - --mount
            - --uts
            - --ipc
            - --net
            - --pid
            - --
            - shutdown 
            - -P
            - now
            image: docker.io/library/alpine
            imagePullPolicy: IfNotPresent
            name: shutdown 
            securityContext:
              privileged: true
          enableServiceLinks: true
          hostIPC: true
          hostNetwork: true
          hostPID: true
          nodeName: toshiba-ubuntu-server-2204
          preemptionPolicy: PreemptLowerPriority
          priority: 0
          restartPolicy: Never
          terminationGracePeriodSeconds: 5
          tolerations:
          - key: CriticalAddonsOnly
            operator: Exists
          - effect: NoExecute
            operator: Exists
  schedule: 0 12 */2 * *
  successfulJobsHistoryLimit: 1
  suspend: false
