apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: lab-cluster
  labels:
    homelab.cluster.x-k8s.io/addons: lab-cluster
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.129.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.128.0.0/16
  controlPlaneEndpoint:
    host: 10.60.80.1
    port: 6443
  topology:
    version: v1.36.5
    classRef:
      name: lab-cluster
    controlPlane:
      replicas: 1
