apiVersion: cluster.x-k8s.io/v1beta2
kind: ClusterClass
metadata:
  name: lab-cluster
spec:
  controlPlane:
    templateRef:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta2
      kind: KubeadmControlPlaneTemplate
      name: lab-cluster-control-plane
    machineInfrastructure:
      templateRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: RemoteMachineTemplate
        name: lab-cluster
  infrastructure:
    templateRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
      kind: RemoteClusterTemplate
      name: lab-cluster
