apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lab-cluster

resources:
- remote-machine-template.yaml
- remote-cluster-template.yaml
- kubeadm-control-plane-template.yaml
- cluster-class.yaml
- addons/cilium
- cluster.yaml

secretGenerator:
- name: lab-cluster-node-scripts
  files:
  - capi-node-cleanup.sh=node-scripts/capi-node-cleanup.sh
  - setup-kube.sh=node-scripts/setup-kube.sh
  - setup-kube-vip.sh=node-scripts/setup-kube-vip.sh
  options:
    labels:
      clusterctl.cluster.x-k8s.io/move: ""

configurations:
- kustomizeconfig.yaml
